# Generated by Django 3.1.2 on 2020-10-20 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='date_finished',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Completed On'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
