# Generated by Django 3.1.2 on 2020-10-20 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201020_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='date_finished',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Round Finished Date'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='date_started',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Round Start Date'),
        ),
    ]
