# Generated by Django 3.1.2 on 2020-10-13 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201013_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_watched',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
