# Generated by Django 3.1.2 on 2020-10-13 23:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20201013_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='chosen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_movie', to=settings.AUTH_USER_MODEL, verbose_name='Chosen By User'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_watched',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date Watched'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Movie Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Already Watched'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='Year Released'),
        ),
    ]
