# Generated by Django 3.1.2 on 2020-10-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201013_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Watched Yet?'),
        ),
    ]
