# Generated by Django 3.1.2 on 2020-10-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201029_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='game_round',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='movies_from_round', to='movies.gameround'),
        ),
    ]
