# Generated by Django 3.1.2 on 2020-11-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201029_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_int', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('rank_string', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userrounddetail',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userrounddetail',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.roundrank'),
        ),
    ]
