# Generated by Django 3.1.2 on 2020-10-14 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_auto_20201013_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviedetail',
            name='heard_of',
            field=models.BooleanField(default=False, verbose_name='Had you heard of this movie before?'),
        ),
        migrations.AlterField(
            model_name='usermoviedetail',
            name='is_user_movie',
            field=models.BooleanField(default=False, verbose_name='Is this your movie?'),
        ),
        migrations.AlterField(
            model_name='usermoviedetail',
            name='seen_previously',
            field=models.BooleanField(default=False, verbose_name='Had you seen this movie previously?'),
        ),
        migrations.AlterField(
            model_name='usermoviedetail',
            name='star_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Previously unknown levels of Deep Hurting...(One Star)'), (2, 'Soul Crippling...(Two Stars)'), (3, 'Damage sustained, but I will recover...(Three Stars)'), (4, 'Rather light on  hurting, actually...(Four Stars)'), (5, "Wow, it didn't hurt at all!!...(Five STars)")], default=3, verbose_name='Deep Hurting Level'),
        ),
        migrations.AlterField(
            model_name='usermoviedetail',
            name='user_guess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_via_guess', to=settings.AUTH_USER_MODEL, verbose_name='Who do you think chose this?'),
        ),
    ]
