# Generated by Django 3.1.2 on 2020-11-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201102_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrounddetail',
            name='movie_average_rating',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
