# Generated by Django 3.1.2 on 2020-11-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_userrounddetail_movie_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrounddetail',
            name='movie_average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, null=True),
        ),
    ]
