# Generated by Django 3.1.2 on 2020-10-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20201014_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviedetail',
            name='heard_of',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Had you heard of this movie before?'),
        ),
        migrations.AlterField(
            model_name='usermoviedetail',
            name='is_user_movie',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Is this your movie?'),
        ),
        migrations.AlterField(
            model_name='usermoviedetail',
            name='seen_previously',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Had you seen this movie previously?'),
        ),
    ]
