# Generated by Django 3.1.2 on 2020-11-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20201103_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsEarned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_int', models.PositiveSmallIntegerField()),
                ('point_string', models.CharField(max_length=300, verbose_name='How Point Was Earned')),
                ('user_round_ob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.userrounddetail')),
            ],
        ),
    ]
