# Generated by Django 3.1.2 on 2020-11-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_pointsearned'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsearned',
            name='point_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Type of Point Earned'),
        ),
    ]
