# Generated by Django 3.1.2 on 2020-10-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20201014_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviedetail',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
