# Generated by Django 3.1.2 on 2020-11-04 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_pointsearned_point_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsearned',
            name='user_round_ob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_earned', to='movies.userrounddetail'),
        ),
    ]
