# Generated by Django 3.1.2 on 2021-03-10 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0011_auto_20201104_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTimeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_run', models.DateTimeField(auto_now_add=True)),
                ('most_disliked_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_time_disliked', to=settings.AUTH_USER_MODEL)),
                ('most_guess_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_time_guess', to=settings.AUTH_USER_MODEL)),
                ('most_liked_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_time_liked', to=settings.AUTH_USER_MODEL)),
                ('most_seen_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_time_seen', to=settings.AUTH_USER_MODEL)),
                ('most_unseen_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_time_unseen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
