# Generated by Django 3.1.2 on 2020-10-15 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0011_auto_20201015_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviedetail',
            name='user_guess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_via_guess', to=settings.AUTH_USER_MODEL, verbose_name='Who do you think chose this? (Leave blank if this is your movie)'),
        ),
    ]
