# Generated by Django 3.1.2 on 2021-03-10 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0012_alltimescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltimescore',
            name='most_rounds_won',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_time_rounds', to=settings.AUTH_USER_MODEL),
        ),
    ]
