# Generated by Django 3.1.2 on 2020-10-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20201015_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviedetail',
            name='heard_of',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'Nope')], default=False, verbose_name='Had you heard of this movie before?'),
        ),
        migrations.AlterField(
            model_name='usermoviedetail',
            name='is_user_movie',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'Nope')], default=False, verbose_name='Is this your movie?'),
        ),
        migrations.AlterField(
            model_name='usermoviedetail',
            name='seen_previously',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'Nope')], default=False, verbose_name='Had you seen this movie previously?'),
        ),
    ]
