# Generated by Django 3.1.2 on 2020-10-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20201015_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviedetail',
            name='star_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'It destroyed me... One Star'), (2, 'New dimensions of suffering... Two Stars'), (3, "Damage sustained, but I'll recover... Three Stars"), (4, 'Surprisingly light on hurting... Four Stars'), (5, "It didn't hurt at all!... Five Stars")], default=3, verbose_name='Deep Hurting Level'),
        ),
    ]
