# Generated by Django 3.1.2 on 2020-10-15 21:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0016_auto_20201015_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviedetail',
            name='user_guess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_via_guess', to=settings.AUTH_USER_MODEL, verbose_name="Who do you think chose this?  (Leave blank if it's your movie)"),
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('current_round', models.BooleanField(default=True)),
                ('date_started', models.DateField(default=datetime.date.today, verbose_name='Started On')),
                ('date_finished', models.DateField(default=datetime.date.today, verbose_name='Completed On')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Winner')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='game_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.gameround'),
            preserve_default=False,
        ),
    ]
