# Generated by Django 3.1.2 on 2020-10-15 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20201015_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='date_finished',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Completed On'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='date_started',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Started On'),
        ),
    ]
