# Generated by Django 3.1.2 on 2020-10-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20201015_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='game_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.gameround'),
        ),
    ]
