# Generated by Django 3.1.2 on 2020-10-15 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20201015_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='current_round',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is this round currently active?'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='date_started',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Round begins on'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='round_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
