# Generated by Django 3.1.2 on 2020-10-16 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0021_auto_20201015_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='participants',
            field=models.ManyToManyField(related_name='rounds_from_user', to=settings.AUTH_USER_MODEL, verbose_name='Participating Members'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_mmg_admin',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'Nope')], default=False),
        ),
    ]
